const dataBase = {
  papel: [ 
    {nombre:"Imagen 02",src:"p02.jpg",alt:"Papel_02"},
    {nombre:"Imagen 01",src:"p01.jpg",alt:"Papel_01"},
    /* {nombre:"Imagen 03",src:"p03.jpg",alt:"Papel_03"}, */
    {nombre:"Imagen 04",src:"p04.jpg",alt:"Papel_04"},
    {nombre:"Imagen 05",src:"p05.jpg",alt:"Papel_05"},
    {nombre:"Imagen 06",src:"p06.jpg",alt:"Papel_06"},
    {nombre:"Imagen 07",src:"p07.jpg",alt:"Papel_07"},
    {nombre:"Imagen 08",src:"p08.jpg",alt:"Papel_08"},
    //{nombre:"Imagen 09",src:"p09.jpg",alt:"Papel_09"},
    {nombre:"Imagen 10",src:"p10.jpg",alt:"Papel_10"},
    {nombre:"Imagen 11",src:"p11.jpg",alt:"Papel_11"},
    {nombre:"Imagen 12",src:"p12.jpg",alt:"Papel_12"},
    {nombre:"Imagen 13",src:"p13.jpg",alt:"Papel_13"},
    {nombre:"Imagen 14",src:"p14.jpg",alt:"Papel_14"},
    //{nombre:"Imagen 15",src:"p15.jpg",alt:"Papel_15"},
    {nombre:"Imagen 16",src:"p16.jpg",alt:"Papel_16"},
    {nombre:"Imagen 17",src:"p17.jpg",alt:"Papel_17"},
    {nombre:"Imagen 18",src:"p18.jpg",alt:"Papel_18"},
    {nombre:"Imagen 19",src:"p19.jpg",alt:"Papel_19"},
    {nombre:"Imagen 20",src:"p20.jpg",alt:"Papel_20"},
    {nombre:"Imagen 21",src:"p21.jpg",alt:"Papel_21"},
    //{nombre:"Imagen 22",src:"p22.jpg",alt:"Papel_22"},
    //{nombre:"Imagen 23",src:"p23.jpg",alt:"Papel_23"},
    {nombre:"Imagen 24",src:"p24.jpg",alt:"Papel_24"},
    {nombre:"Imagen 25",src:"p25.jpg",alt:"Papel_25"},
    {nombre:"Imagen 26",src:"p26.jpg",alt:"Papel_26"},
    {nombre:"Imagen 27",src:"p27.jpg",alt:"Papel_27"},
    {nombre:"Imagen 29",src:"p29.jpg",alt:"Papel_29"},
    {nombre:"Imagen 29",src:"p29.jpg",alt:"Papel_29"},
    {nombre:"Imagen 30",src:"p30.jpg",alt:"Papel_30"},
    {nombre:"Imagen 31",src:"p31.jpg",alt:"Papel_31"},
    {nombre:"Imagen 32",src:"p32.jpg",alt:"Papel_32"},
    {nombre:"Imagen 33",src:"p33.jpg",alt:"Papel_33"},
    {nombre:"Imagen 34",src:"p34.jpg",alt:"Papel_34"},
    {nombre:"Imagen 35",src:"p35.jpg",alt:"Papel_35"},
    {nombre:"Imagen 36",src:"p36.jpg",alt:"Papel_36"},
    {nombre:"Imagen 37",src:"p37.jpg",alt:"Papel_37"},
    {nombre:"Imagen 38",src:"p38.jpg",alt:"Papel_38"},
    {nombre:"Imagen 39",src:"p39.jpg",alt:"Papel_39"},
    {nombre:"Imagen 40",src:"p40.jpg",alt:"Papel_40"},
    {nombre:"Imagen 41",src:"p41.jpg",alt:"Papel_41"},
    {nombre:"Imagen 42",src:"p42.jpg",alt:"Papel_42"},
    {nombre:"Imagen 43",src:"p43.jpg",alt:"Papel_43"},
    {nombre:"Imagen 44",src:"p44.jpg",alt:"Papel_44"},
    {nombre:"Imagen 45",src:"p45.jpg",alt:"Papel_45"},
  ],
  feria: [
    {nombre:"Imagen 01",src:"f01.jpg",alt:"Feria_01"},
    {nombre:"Imagen 02",src:"f02.jpg",alt:"Feria_02"},
    {nombre:"Imagen 03",src:"f03.jpg",alt:"Feria_03"},
    {nombre:"Imagen 04",src:"f04.jpg",alt:"Feria_04"},
    {nombre:"Imagen 05",src:"f05.jpg",alt:"Feria_05"},
    {nombre:"Imagen 06",src:"f06.jpg",alt:"Feria_06"},
    {nombre:"Imagen 07",src:"f07.jpg",alt:"Feria_07"},
    {nombre:"Imagen 08",src:"f08.jpg",alt:"Feria_08"},
    {nombre:"Imagen 09",src:"f09.jpg",alt:"Feria_09"},
    {nombre:"Imagen 10",src:"f10.jpg",alt:"Feria_10"},
    {nombre:"Imagen 11",src:"f11.jpg",alt:"Feria_11"},
    {nombre:"Imagen 12",src:"f12.jpg",alt:"Feria_12"},
    {nombre:"Imagen 13",src:"f13.jpg",alt:"Feria_13"},
    {nombre:"Imagen 14",src:"f14.jpg",alt:"Feria_14"}
    //{nombre:"Imagen 15",src:"f15.jpg",alt:"Feria_15"}
  ],
  telaAgua: [
    {nombre:"Imagen 01",src:"ta01.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 02",src:"ta02.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 03",src:"ta03.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 04",src:"ta04.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 05",src:"ta05.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 06",src:"ta06.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 07",src:"ta07.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 08",src:"ta08.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 09",src:"ta09.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 10",src:"ta10.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 11",src:"ta11.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 12",src:"ta12.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 13",src:"ta13.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 14",src:"ta14.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 15",src:"ta15.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 16",src:"ta16.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 17",src:"ta17.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 18",src:"ta18.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 19",src:"ta19.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 20",src:"ta20.jpg",alt:"Tinta al Agua"},
    {nombre:"Imagen 21",src:"ta21.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 22",src:"ta22.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 23",src:"ta23.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 24",src:"ta24.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 25",src:"ta25.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 26",src:"ta26.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 27",src:"ta27.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 28",src:"ta28.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 29",src:"ta29.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 30",src:"ta30.jpg",alt:"Tinta al Agua"}, 
    {nombre:"Imagen 31",src:"ta31.jpg",alt:"Tinta al Agua"},    
  ],
  telaPlastisol: [
    {nombre:"Imagen 01",src:"tp01.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 02",src:"tp02.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 03",src:"tp03.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 04",src:"tp04.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 05",src:"tp05.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 06",src:"tp06.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 07",src:"tp07.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 08",src:"tp08.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 09",src:"tp09.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 10",src:"tp10.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 11",src:"tp11.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 12",src:"tp12.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 13",src:"tp13.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 14",src:"tp14.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 15",src:"tp15.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 16",src:"tp16.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 17",src:"tp17.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 18",src:"tp18.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 19",src:"tp19.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 20",src:"tp20.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 21",src:"tp21.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 22",src:"tp22.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 23",src:"tp23.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 24",src:"tp24.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 25",src:"tp25.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 26",src:"tp26.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 27",src:"tp27.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 28",src:"tp28.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 29",src:"tp29.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 30",src:"tp30.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 31",src:"tp31.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 32",src:"tp32.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 33",src:"tp33.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 34",src:"tp34.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 35",src:"tp35.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 36",src:"tp36.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 37",src:"tp37.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 38",src:"tp38.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 39",src:"tp39.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 40",src:"tp40.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 41",src:"tp41.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 42",src:"tp42.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 43",src:"tp43.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 44",src:"tp44.jpg",alt:"Tinta Plastisol"},
    //{nombre:"Imagen 45",src:"tp45.jpg",alt:"Tinta Plastisol"},    
    {nombre:"Imagen 46",src:"tp46.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 47",src:"tp47.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 48",src:"tp48.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 49",src:"tp49.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 50",src:"tp50.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 51",src:"tp51.jpg",alt:"Tinta Plastisol"},
    {nombre:"Imagen 52",src:"tp52.jpg",alt:"Tinta Plastisol"},
    
  ],
}

export default dataBase;
